packages:
  - apps/*
  - services/*
  - packages/*
  - acceptance

linkWorkspacePackages: false

allowBuilds:
  esbuild: true

onlyBuiltDependencies:
  - esbuild

minimumReleaseAgeExclude:
  - '@mmverick123/lowcode'
